FROM rust:latest

RUN useradd -s /bin/bash -m vscode \
    && groupadd docker && usermod -aG docker,sudo vscode \
    && mkdir -p /app \
    && chown -R vscode:docker /app
WORKDIR /app

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y build-essential clang gcc git libssl-dev llvm make pkg-config xz-utils

RUN git clone https://github.com/AleoHQ/snarkOS.git --depth 1 \
    && cd snarkOS \
    && cargo build --release

USER vscode